baseURL = "https://fanyuuwang.github.io/"
languageCode = "en-us"
title = "Fanyu Wang"
theme = "github.com/geekifan/zero-academic-page"

[params]
  author = "Fanyu Wang"
  description = "PhD Student at HumanISE Lab, Monash University."
  
  # Profile details
  avatar = "images/profile.png"
  role = "PhD Student"
  organization = "Monash University"

  # Social Links
  [[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    url = "mailto:fanyu.wang@monash.edu"
  
  [[params.social]]
    name = "Google Scholar"
    icon = "ai ai-google-scholar"
    url = "https://scholar.google.com.au/citations?user=KoVjTacAAAAJ&hl=en"
  
  [[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/fanyuuwang/"

  [[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    url = "https://github.com/fanyuuwang"
